-- MySQL Script generated by MySQL Workbench
-- jue 03 may 2018 01:30:49 CEST
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema db_inmobiliaria
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema db_inmobiliaria
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db_inmobiliaria` DEFAULT CHARACTER SET utf8 ;
USE `db_inmobiliaria` ;

-- -----------------------------------------------------
-- Table `db_inmobiliaria`.`rol`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_inmobiliaria`.`rol` ;

CREATE TABLE IF NOT EXISTS `db_inmobiliaria`.`rol` (
  `_id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(32) NOT NULL,
  PRIMARY KEY (`_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_inmobiliaria`.`usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_inmobiliaria`.`usuario` ;

CREATE TABLE IF NOT EXISTS `db_inmobiliaria`.`usuario` (
  `_id` INT NOT NULL AUTO_INCREMENT,
  `login` VARCHAR(64) NOT NULL,
  `clave` VARCHAR(256) NOT NULL,
  `email` VARCHAR(64) NOT NULL,
  `dni` VARCHAR(9) NOT NULL,
  `nombre` VARCHAR(64) NOT NULL,
  `apellidos` VARCHAR(128) NOT NULL,
  `f_nacimiento` DATE NOT NULL,
  `sexo` TINYINT(1) NOT NULL,
  `direccion` VARCHAR(128) NOT NULL,
  `telefono` VARCHAR(16) NOT NULL,
  `rol` INT NOT NULL,
  `f_creacion` DATETIME NOT NULL DEFAULT NOW(),
  PRIMARY KEY (`_id`),
  INDEX `fk_usuario_rol_idx` (`rol` ASC),
  CONSTRAINT `fk_usuario_rol`
    FOREIGN KEY (`rol`)
    REFERENCES `db_inmobiliaria`.`rol` (`_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `db_inmobiliaria`.`rol`
-- -----------------------------------------------------
START TRANSACTION;
USE `db_inmobiliaria`;
INSERT INTO `db_inmobiliaria`.`rol` (`_id`, `nombre`) VALUES (1, 'Huesped');
INSERT INTO `db_inmobiliaria`.`rol` (`_id`, `nombre`) VALUES (2, 'Anfitrion');

COMMIT;

