-- MySQL Script generated by MySQL Workbench
-- mié 09 may 2018 14:12:21 CEST
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema db_inmobiliaria
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema db_inmobiliaria
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db_inmobiliaria` DEFAULT CHARACTER SET utf8 COLLATE utf8_spanish_ci ;
USE `db_inmobiliaria` ;

-- -----------------------------------------------------
-- Table `db_inmobiliaria`.`rol`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_inmobiliaria`.`rol` ;

CREATE TABLE IF NOT EXISTS `db_inmobiliaria`.`rol` (
  `_id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(32) NOT NULL,
  PRIMARY KEY (`_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_spanish_ci;


-- -----------------------------------------------------
-- Table `db_inmobiliaria`.`usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_inmobiliaria`.`usuario` ;

CREATE TABLE IF NOT EXISTS `db_inmobiliaria`.`usuario` (
  `_id` INT NOT NULL AUTO_INCREMENT,
  `login` VARCHAR(64) NOT NULL,
  `clave` VARCHAR(256) NOT NULL,
  `email` VARCHAR(64) NOT NULL,
  `dni` VARCHAR(9) NOT NULL,
  `nombre` VARCHAR(64) NOT NULL,
  `apellidos` VARCHAR(128) NOT NULL,
  `f_nacimiento` DATE NOT NULL,
  `sexo` TINYINT(1) NOT NULL,
  `direccion` VARCHAR(128) NOT NULL,
  `telefono` VARCHAR(16) NOT NULL,
  `rol` INT NOT NULL,
  `f_creacion` DATETIME NOT NULL DEFAULT NOW(),
  `activo` TINYINT(1) NOT NULL,
  PRIMARY KEY (`_id`),
  INDEX `fk_usuario_rol_idx` (`rol` ASC),
  CONSTRAINT `fk_usuario_rol`
    FOREIGN KEY (`rol`)
    REFERENCES `db_inmobiliaria`.`rol` (`_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_spanish_ci;


-- -----------------------------------------------------
-- Table `db_inmobiliaria`.`tipo_apartamento`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_inmobiliaria`.`tipo_apartamento` ;

CREATE TABLE IF NOT EXISTS `db_inmobiliaria`.`tipo_apartamento` (
  `_id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_spanish_ci;


-- -----------------------------------------------------
-- Table `db_inmobiliaria`.`apartamento`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_inmobiliaria`.`apartamento` ;

CREATE TABLE IF NOT EXISTS `db_inmobiliaria`.`apartamento` (
  `_id` INT NOT NULL AUTO_INCREMENT,
  `anfitrion` INT NOT NULL,
  `descripcion` VARCHAR(256) NOT NULL,
  `direccion` VARCHAR(128) NOT NULL,
  `poblacion` VARCHAR(128) NOT NULL,
  `pais` VARCHAR(128) NOT NULL,
  `tipo_apartamento` INT NOT NULL,
  `aseos` INT NULL,
  `dormitorios` INT NULL,
  `m2` INT NULL,
  `garaje` TINYINT(1) NULL,
  `mascotas` TINYINT(1) NULL,
  `amueblado` TINYINT(1) NULL,
  `piscina` TINYINT(1) NULL,
  `jardin` TINYINT(1) NULL,
  `trastero` TINYINT(1) NULL,
  `ascensor` TINYINT(1) NULL,
  PRIMARY KEY (`_id`),
  INDEX `fk_apartamento_usuario1_idx` (`anfitrion` ASC),
  INDEX `fk_apartamento_tipo_apartamento1_idx` (`tipo_apartamento` ASC),
  CONSTRAINT `fk_apartamento_usuario1`
    FOREIGN KEY (`anfitrion`)
    REFERENCES `db_inmobiliaria`.`usuario` (`_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_apartamento_tipo_apartamento1`
    FOREIGN KEY (`tipo_apartamento`)
    REFERENCES `db_inmobiliaria`.`tipo_apartamento` (`_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_spanish_ci;


-- -----------------------------------------------------
-- Table `db_inmobiliaria`.`foto_apartamento`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_inmobiliaria`.`foto_apartamento` ;

CREATE TABLE IF NOT EXISTS `db_inmobiliaria`.`foto_apartamento` (
  `_id` INT NOT NULL AUTO_INCREMENT,
  `apartamento` INT NOT NULL,
  `nombre` VARCHAR(128) NOT NULL,
  `foto` MEDIUMBLOB NOT NULL,
  PRIMARY KEY (`_id`),
  INDEX `fk_foto_apartamento_apartamento1_idx` (`apartamento` ASC),
  CONSTRAINT `fk_foto_apartamento_apartamento1`
    FOREIGN KEY (`apartamento`)
    REFERENCES `db_inmobiliaria`.`apartamento` (`_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_spanish_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `db_inmobiliaria`.`rol`
-- -----------------------------------------------------
START TRANSACTION;
USE `db_inmobiliaria`;
INSERT INTO `db_inmobiliaria`.`rol` (`_id`, `nombre`) VALUES (1, 'Huesped');
INSERT INTO `db_inmobiliaria`.`rol` (`_id`, `nombre`) VALUES (2, 'Anfitrion');

COMMIT;


-- -----------------------------------------------------
-- Data for table `db_inmobiliaria`.`tipo_apartamento`
-- -----------------------------------------------------
START TRANSACTION;
USE `db_inmobiliaria`;
INSERT INTO `db_inmobiliaria`.`tipo_apartamento` (`_id`, `nombre`) VALUES (1, 'Casa');
INSERT INTO `db_inmobiliaria`.`tipo_apartamento` (`_id`, `nombre`) VALUES (2, 'Piso');
INSERT INTO `db_inmobiliaria`.`tipo_apartamento` (`_id`, `nombre`) VALUES (3, 'Chalet');
INSERT INTO `db_inmobiliaria`.`tipo_apartamento` (`_id`, `nombre`) VALUES (4, 'Solar');
INSERT INTO `db_inmobiliaria`.`tipo_apartamento` (`_id`, `nombre`) VALUES (5, 'Otro');

COMMIT;

